export const CONTUCT_LOADING='CONTUCT_LOADING'
export const CONTUCT_SUCCESS='CONTUCT_SUCCESS'
export const CONTUCT_FAIL='CONTUCT_FAIL'

export const LOGIN_LOADING='LOGIN_LOADING'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'

export const REGISTER_LOADING='REGISTER_LOADING'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const APPOINTMENT_LOADING='APPOINTMENT_LOADING'
export const APPOINTMENT_SUCCESS='APPOINTMENT_SUCCESS'
export const APPOINTMENT_FAIL='APPOINTMENT_FAIL'

export const APPOINTMENT_LIST='APPOINTMENT_LIST'

export const LOGOUT='LOGOUT'

